profile = "custom"
artifacts_folder = "artifacts"

[msbuild]
project = "../WinSyncScroll/WinSyncScroll.csproj"
configuration = "Release"

[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = false
SelfContained = true
PublishReadyToRun = true
CopyOutputSymbolsToPublishDirectory = false
SkipCopyingSymbolsToOutputDirectory = true

[github]
user = "magicxor"
repo = "WinSyncScroll"

[nuget]
publish = false

[[pack]]
rid = ["win-x64", "win-arm64"]
kinds = ["zip"]

[scoop]
publish = false
