profile = "custom"
artifacts_folder = "artifacts"

[msbuild]
project = "../WinSyncScroll/WinSyncScroll.csproj"
configuration = "Release"

[github]
user = "magicxor"
repo = "WinSyncScroll"

[nuget]
publish = false

[[pack]]
rid = ["win-x64", "win-arm64"]
kinds = ["zip"]
